### ISSUE TITLE
Make EULA only prompt once per Osprey install

### ISSUE THREAD

**Issue by syne0** [syne0/osprey#16]
In HAWK, the EULA would prompt every time you ran it. Lets not do that. 

My best idea was to use the existing Add-OspreyAppData, Read-OspreyAppData, and Out-OspreyAppData to store the EULA consent flag in the osprey.json file in appdata, which is where the IP Lookup API key is stored. Unfortunately this is causing many errors.

**Comment by DevonChorney** [comment]
Feature added in Dev
