### ISSUE TITLE
Osprey errors with reference to Azure.core.dll

### ISSUE THREAD

**Issue by syne0** [syne0/osprey#28]
When running Osprey with the most up to date graph and EXO modules, you may get an error referencing Azure.core.dll.

Temporary fix is to downgrade either EXO to 3.4.0, or Graph to 2.19.0.

Ultimately the fix is up to Microsoft as it's an issue with their modules.

**Comment by syne0** [comment]
probably fixed in newest eop preview, needs testinggg

**Comment by DevonChorney** [comment]
Fixed applied in dev
